### ISSUE TITLE
Provide a command like IfFontAvaiblable

### ISSUE THREAD

**Issue by MaxNoe** [wspr/fontspec#226] opened 2016-02-19 08:58 UTC
This would be a huge help:

``` latex

\IfFontAvailable{Comic Sans MS}{
    \setmainfont{Comic Sans MS}
}{
    \setmainfont{Latin Modern Roman}
}
```

**Comment by davidcarlisle** [comment] 2016-02-19 09:15
This is a duplicate of issue #207 I think (and yes it would be useful!)

**Comment by wspr** [comment] 2016-02-19 09:23
Okay okay I'll write something `:)`
I think the syntax suggested above is pretty much as good as it'd get.

**Comment by wspr** [comment] 2016-02-19 09:28
Although whenever I start thinking about this feature I run into edge cases. It would be easier to write this somehow so it's clear that it's a plain font call in the branch, nothing fancy like fontspec does.

I.e., should you have to write

    \IfFontAvailable{[texgyrepagella-regular.otf]} ...

or

    \IfFontAvailable{texgyrepagella-regular.otf} ...

(i.e., detect the `.otf` and insert the square brackets automatically). I'm thinking the latter, but is there anything else I need to take into account? Maybe not. I guess I can think some more about it.

**Comment by MaxNoe** [comment] 2016-09-09 07:13
Principle of least surprise would be , if it took the same AS all those `\set*font` commands

**Closed** 2016-12-27 11:57 UTC
